apiVersion: apps/v1
kind: Deployment
metadata:
  name: nong-kai-deployment
  namespace: nonprod
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nong-kai-api-nonprod
      app.kubernetes.io/env: nonprod
      app.kubernetes.io/managed-by: kustomize
  template:
    metadata:
      labels:
        app: nong-kai-api-nonprod
        app.kubernetes.io/env: nonprod
        app.kubernetes.io/managed-by: kustomize
    spec:
      containers:
        - name: nong-kai-api-nonprod
          image: anonja/js-web-app:74e8f87
          ports:
            - containerPort: 3000
